# publish.yml
# SwiftUIHelpers
#
# Copyright © 2025 Dagitali LLC. All rights reserved.
#
# A GitHub Actions workflow file that automates publishing software projects.
#
# See:
# 1. https://github.com/actions
# 2. https://github.com/features/actions
# 3. https://github.com/marketplace/actions/gitflow-workflow-action
# 4. https://docs.github.com/en/actions

---

name: Publish

on:
  push:               # Allow automatic triggering for pushes.
    tags:
      - v*.*.*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: "Automated release for version ${{ github.ref_name }}."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
